### ISSUE TITLE
Hard mode?

### ISSUE THREAD

**Issue by victorhartman** [pingiun/woordle#10]
In de originele wordle zit ook een 'hard mode' die je forceert om elke hint te gebruiken. Kan dit ook aan woordle toegevoegd worden?

Dank voor maken van woordle, waardeer het enorm!

**Comment by pingiun** [comment]
Ik snap dat mensen dit willen maar ik denk dat sommige woorden niet goed op te lossen zijn in hard mode. Ik denk juist dat strategie gebruiken waarbij je veel letters in 1 woord uitsluit de hard mode hoort te zijn, wat je bij sommige woorden wel nodig hebt
