### ISSUE TITLE
Weergave van herhaalde letters binnen één poging

### ISSUE THREAD

**Issue by cwverhey** [pingiun/woordle#14]
Zoals te zien in de eerste regel van het voorbeeld hieronder, wordt bij een poging waarin 2x dezelfde letter wordt gebruikt, slechts 1x de juiste hint gegeven.

Volgens de uitleg is dit de betekenis van de twee N'en:
De letter N zit helemaal niet in het woord.
De letter N zit in het woord maar op een andere plek.

Overigens mis ik collation van woorden als 'ruïnes' naar 'ruines' in de dictionary; wel de standaard in puzzelgebruik. Toevallig is 'ruinen' ook een bestaand woord anders dan als meervoud van 'ruïne'.

![telegram-cloud-photo-size-4-6046110683776530165-y](https://user-images.githubusercontent.com/27963134/152579562-9e4ab3ce-db99-4257-a211-293683b371b4.jpg)

**Comment by pingiun** [comment]
Ik zou de uitleg iets anders kunnen verwoorden. Maar als er beide `N`en geel waren zou het betekenen dat de letter N twee keer in het woord zit en allebei op een andere plek.

Ik zal ruines toevoegen aan de woordenlijst. Als je meer woorden tegenkomt die missen vanwege accenten hoor ik het graag

**Comment by pingiun** [comment]
Ik ga de hulptekst niet aanpassen want ik geloof dat het duidelijk genoeg is
