### ISSUE TITLE
Woorden met accenten

### ISSUE THREAD

**Issue by cwverhey** [pingiun/woordle#15]
> Als je meer woorden tegenkomt die missen vanwege accenten hoor ik het graag
_Originally posted by @pingiun in https://github.com/pingiun/woordle/issues/14#issuecomment-1030276663_

Volgens mij missen praktisch alle woorden met accenten. Een snelle zoektocht door een beperkte woordenlijst geeft me 49 woorden van 5 letters met een accent erin, waarvan er maar 7 in de woordenlijst staan.

Ik wil best een poging doen om nog meer missende woorden te vinden. Voor een zo volledig mogelijk resultaat: kan je vertellen op basis van welke dataset de huidige woordenlijst is samengesteld?

**Comment by pingiun** [comment]
Gefixt in 4d6f8e4afb435c3de5843908aae9100f35c71c0a
