### ISSUE TITLE
https://woordle.nl/woordle6/ Isn’t working 

### ISSUE THREAD

**Issue by Bullet55NL** [pingiun/woordle#2]
It appears that https://woordle.nl/woordle6/ isn’t working on my phone. 
![8899113D-E569-47AC-A0C1-70E1BD4DBEC9](https://user-images.githubusercontent.com/42201487/149029118-ebbef38a-c734-424e-bc30-596f0fdca674.png)

**Comment by pingiun** [comment]
Bedankt! Gefixt in https://github.com/pingiun/woordle/commit/9ad2e38dfc3a500c420f967a860b6eaecf4f9a0d

**Comment by pingiun** [comment]
Over een paar minuutjes is de fix online
