### ISSUE TITLE
Woordle6 77 kan niet geraden worden

### ISSUE THREAD

**Issue by joverwijk** [pingiun/woordle#20]
De Nederlandse Woordle6 77 is 'played', maar tijdens het raden wordt dit woord aangegeven als 'onbekend woord'. Hierdoor is het logischerwijs niet eens mogelijk te winnen. Curieus is dat dit woord alleen voorkomt in `puzzle-words6` (Nederlands en Engels) en in `all-words-en`, maar niet in de Nederlandse `all-words`.

**Comment by rogierhofboer** [comment]
Ik kan dit bevestigen. Ik wist niet dat het played zou moeten zijn, maar heb pla.e. en kom niet verder met de nog mogelijke letters (zit y en d bij)

**Comment by rogierhofboer** [comment]
FYI Er is nu een ander 6 letter woord voor vandaag dat wel geraden kan worden.

**Comment by pingiun** [comment]
Gefixt in https://github.com/pingiun/woordle/commit/05d920a4964830f5486420e0d4e9a358021b8a1a
