### ISSUE TITLE
Woordle6 110 kan niet geraden worden

### ISSUE THREAD

**Issue by joverwijk** [pingiun/woordle#21]
Dit keer kan Woordle6 110 niet geraden worden. Het correcte woord is 'hiatus', maar ik kan alleen 'status' en 'flatus' invoeren. Hiermee lijkt het alsof de server een woord kiest uit de lijst 'puzzle-words6' (waar 'hiatus' in voorkomt, inclusief een paar andere op -atus). De input lijkt echter te worden vergeleken met woorden uit de lijst 'all-words6', waar slechts 'status' en 'flatus' in voorkomen. Misschien handiger om één lijst te gebruiken? Dan zit je sowieso goed.

**Comment by renskemarij** [comment]
> Dit keer kan Woordle6 110 niet geraden worden. Het correcte woord is 'hiatus', maar ik kan alleen 'status' en 'flatus' invoeren. Hiermee lijkt het alsof de server een woord kiest uit de lijst 'puzzle-words6' (waar 'hiatus' in voorkomt, inclusief een paar andere op -atus). De input lijkt echter te worden vergeleken met woorden uit de lijst 'all-words6', waar slechts 'status' en 'flatus' in voorkomen. Misschien handiger om één lijst te gebruiken? Dan zit je sowieso goed.

Wel logisch dat hij twee verschillende lijsten gebruikt, ik neem aan dat zijn doel is dat je super obscure woorden mag invoeren als raadpogingen maar dat de oplossingen altijd algemeen bekende woorden zijn (dus puzzle-words is een kleinere subset van all-words). Maar om issues te voorkomen zoals vandaag met hiatus, zou het goed zijn om een testje in te bouwen om voor publicatie te checken of alle woorden in puzzle-words6 ook daadwerkelijk voorkomen in all-words 6.

**Comment by RensOliemans** [comment]
Het lijkt er op dat van de 3858 puzzelwoorden (`puzzle-words6`) er 1267 niet in `all-words6` zitten. Hier beneden zijn de eerste tien, en hun indexen.

**Spoilers** voor de puzzel van vandaag, die van over 12 dagen, en een aantal puzzels over ~4 maanden.

    [('hiatus', 109),
     ('indica', 121),
     ('deluxe', 231),
     ('laetus', 237),
     ('abdita', 239),
     ('brugge', 240),
     ('aspera', 241),
     ('fortis', 242),
     ('steini', 243),
     ('davisi', 245)]

Sowieso worden de woorden in `puzzle-words6` behoorlijk obscuur vanaf ~240. Ik weet niet hoe dat het beste opgelost kan worden, ik kan wel even een kleine fix maken dat hij in ieder geval deze 1267 woorden in `all-words6` zet, dan zijn ze in ieder geval mogelijk om te raden.

**Comment by RensOliemans** [comment]
Bij nader inzien is het waarschijnlijk beter om ze uit de `puzzle`-lijst te halen, in plaats van ze in de `all-words` te zetten. Dat maakt de `puzzle`-lijst wel wat kleiner, en grote kans dat er alsnog redelijk obscure woorden in zitten, maar dan zijn de aller-obscuurste in ieder geval weggehaald.

**Comment by pingiun** [comment]
> Wel logisch dat hij twee verschillende lijsten gebruikt, ik neem aan dat zijn doel is dat je super obscure woorden mag invoeren als raadpogingen maar dat de oplossingen altijd algemeen bekende woorden zijn (dus puzzle-words is een kleinere subset van all-words).

Dat klopt!

> Maar om issues te voorkomen zoals vandaag met hiatus, zou het goed zijn om een testje in te bouwen om voor publicatie te checken of alle woorden in puzzle-words6 ook daadwerkelijk voorkomen in all-words 6.

Dit is inderdaad hoe ik het heb opgelost, in eb33bc801cafc9ec6f3536a151c66a447f3dc70f
