### ISSUE TITLE
Paar kleine taalfouten

### ISSUE THREAD

**Issue by richy58729** [pingiun/woordle#28]
Hoi Jelle,

Allereerst, bedankt voor het maken van Woordle.

Ik wil je wijzen op twee taalfoutjes in de instellingen:
1. hoog contrast vakjes &rarr; hoogcontrastvakjes (vergelijk met 'langeafstandsraket'; zie ook [woordgroep in samenstelling](https://woordenlijst.org/leidraad/6/7))
1. toetsenbord letters &rarr; toetsenbordletters (een gewone samenstelling, dus moet aan elkaar geschreven worden)

**Comment by pingiun** [comment]
Dankjewel, dit kan ik wel even regelen

**Comment by pingiun** [comment]
Opgelost in 10d6e2c4ebc1d13b3f66999e16bb7633171d779e

**Comment by richy58729** [comment]
> Opgelost in [10d6e2c](https://github.com/pingiun/woordle/commit/10d6e2c4ebc1d13b3f66999e16bb7633171d779e)

Niet helemaal ... Ook als je het woord 'hoog' vervangt door 'hoger', is het nog steeds een samenstelling en moet het geschreven worden als 'hogercontrastvakjes'. Onze Taal legt het misschien duidelijker uit in dit artikel: [https://onzetaal.nl/taalloket/langeafstandsloper](https://onzetaal.nl/taalloket/langeafstandsloper).

**Comment by pingiun** [comment]
Ik lees het misschien anders, wat gebeurt er nadat je de instelling aan zet? Dan hebben de vakjes hoger contrast. Het is dus niet één ding maar beschrijft wat de instelling doet

**Comment by richy58729** [comment]
'hoog contrast vakjes' of 'hoger contrast vakjes' is gewoonweg taalkundig incorrect.
Je kunt op zijn hoogst beargumenteren dat het telegramstijl is, zoals in een krantenkop, en dan betekent het eigenlijk zoiets als 'hoger contrast van de vakjes', maar ik vind dat nogal vergezocht. Ik lees het in ieder geval en denk: 'Dit is incorrect' en denk vervolgens niet: '... maar als ik het interpreteer als telegramstijl, ja oké, dan kan het wel'. Telegramstijl is geen correct Nederlands, het is telegramstijl.
Ik kan me niet vinden in het argument dat het niet één ding is. 'hoogcontrastvakjes' zijn vakjes met hoog contrast, dus één ding, en 'vakjes' zijn vakjes, dus ook één ding, net zoals een 'langeafstandsraket' één ding is, nl. een raket voor de lange afstand, en 'raket' één ding is, nl. een raket.
Schrijf het als 'hoogcontrastvakjes' of 'hogercontrastvakjes' en het is gewoon correct Nederlands zonder je in een telegramstijlbocht te moeten wringen om het kloppend te krijgen. Of schrijf het desnoods als 'vakjes met hoog contrast' of 'vakjes met hoger contrast', dan heb je maar één woord extra toegevoegd (en kost het je slechts drie letters en een spatie extra) en is het ineens correct Nederlands.

**Comment by pingiun** [comment]
Het is "Verhoogd contrast" geworden in bb67c92c465e7a4a2ef38867ddafb916aaca862d

**Comment by richy58729** [comment]
👍
