### ISSUE TITLE
console.log(todays_word) ?

### ISSUE THREAD

**Issue by TheCad** [pingiun/woordle#3]
![image](https://user-images.githubusercontent.com/2212054/149140409-6dcc9afa-79e0-49ee-a243-f4041a9e697b.png)
Lijkt me niet de bedoeling?

**Comment by pingiun** [comment]
als je wil cheaten kan je ook https://github.com/pingiun/woordle/blob/main/data/puzzle-words gewoon bekijken, lijkt me niet nodig om anticheat dingen te implementeren
