### ISSUE TITLE
Klein toetsenbord dankzij advertenties

### ISSUE THREAD

**Issue by svenluijten** [pingiun/woordle#30]
Vanochtend verschenen er plotseling advertenties zowel boven als onder het toetsenbord van Woordle (5 letters). Dit had als gevolg dat de toetsen een stuk kleiner waren dan normaal. 

![image](https://github.com/pingiun/woordle/assets/11269635/deca171a-6eb2-4f88-a1f0-1ad71ee26650)

Dit is op een iPhone 12 Pro, maar meerdere mensen met verschillende andere toestellen hebben er ook last van.

**Comment by pingiun** [comment]
De advertenties heb ik inderdaad geplaatst, maar met de plaatsing moet ik nog even knoeien. Ik hoop dat het binnenkort allemaal weer goed werkt op mobiel

**Comment by svenluijten** [comment]
Top, geen probleem! Hopelijk helpen de advertenties om de serverkosten wat te dragen. 😄

**Comment by svenluijten** [comment]
De laatste tijd lijkt dit geen probleem meer voor me te zijn, dus ik sluit het issue  :)
