### ISSUE TITLE
Laatste poging over te slaan met enter

### ISSUE THREAD

**Issue by Kartoffel** [pingiun/woordle#5]
Hoi! Leuke website, erg verslavend.

Ik heb op de een-na-laatste poging iets te nerveus op enter gedrukt en daarbij schijnbaar twee keer de toets bediend. Het blijkt dat je daarmee de laatste poging over kunt slaan, en direct naar game-over gaat :(

**Stappen om te reproduceren:**

1. Open Woordle
2. Maak vijf pogingen en laat de zesde poging leeg
3. Druk op ENTER (scherm- of toetsenbordtoets)

**Screenshots:**

![](https://i.imgur.com/vsvOejV.png)

![](https://i.imgur.com/4lUxFX2.png)

**Comment by pingiun** [comment]
Bedankt! Ik hoorde al van iemand dat dit mogelijk was maar dit is een heel duidelijke bug report, ik denk dat ik het wel kan oplossen

**Comment by pingiun** [comment]
Nogmaals bedankt! Gefixt in fe7b44b630ddd4d401721071b66bf761c5d524c7
