### ISSUE TITLE
De ij ontbreekt

### ISSUE THREAD

**Issue by pebbe** [pingiun/woordle#7]
Op het toetsenbord ontbreekt de letter ij, en als ik het als i-j intik krijg ik twee aparte letters.

**Comment by pingiun** [comment]
Hoi Pebbe, ik heb hier bij het ontwerpen van Woordle niet goed over nagedacht en het zou nu een te grote verandering zijn. Elke keer dat een woord IJ gebruikt wordt dit geteld als 2 letters
